### PR TITLE
fixed some typos and altered readme to comply with markdown best practices

### PR DESCRIPTION
**Pull request by dotFionn**

### CODE REVIEW

**Comment by merlinschumacher** [comment]
Thank you for your help!

**Comment by merlinschumacher** [comment]
Hey, 

this is off-topic, but I want to change the project's license from the GPL2 to AGPL to make sure that people who use the project only as an API have to make contributions to the project. Since you are a contributor, I have to ask if you are okay with that change.
Best regards

Merlin

**Comment by dotFionn** [comment]
Hey Merlin,

to my understanding of the license according to [choosealicense.com](https://choosealicense.com/licenses/agpl-3.0/) a potential API-only user has to credit the data source and has to disclose the full source if modifications to the source have been done.

If that is what you want to achieve and what your understanding of the license is, then **I support the license change**.

If that is not also your understanding, I'll have to take a deeper look into the licenses, as I have not been too deeply involved in licensing stuff.

Best greetings

Fionn

**Comment by merlinschumacher** [comment]
Exactly that is the intent of the license change. Thanks for your support :)

**Pull request merged**
